<center><h2><strong><font color="blue"> Advanced Programming for Data Science (APDS)</font></strong></h2></center>

<center><img alt="" src="images/covers/taudata-cover.jpg"/></center>

<center><h2><strong><font color="blue">APDS-05: Introduction to Pandas for Data Science</font></strong></h2></center>

<b><center><h3>(C) Taufik Sutanto</h3></center>
* .

In [ ]:
!pip install pandas seaborn numpy matplotlib --q

In [1]:
# Importing Some Python Modules
import warnings; warnings.simplefilter('ignore')
import pandas as pd, numpy as np, seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('bmh'); sns.set()
np.random.seed(420)

# <center><font color="blue"> Pandas DataFrame</font></center>

<center><img alt="" src="images/pandas_dataframe_structure.jpg" style="height: 350px;" /></center>

* A Pandas DataFrame can be constructed from a **Dictionary** or a **List/Tuple**

In [86]:
# DataFrame from Dictionary
D = {'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU']} 
df = pd.DataFrame(D)
df

        Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2    Shaurya   22         DU
3   Shivangi   21        BHU

In [89]:
df.describe(include="all")

         Name        Age University
count       4   4.000000          4
unique      4        NaN          3
top     Ankit        NaN        BHU
freq        1        NaN          2
mean      NaN  21.750000        NaN
std       NaN   0.957427        NaN
min       NaN  21.000000        NaN
25%       NaN  21.000000        NaN
50%       NaN  21.500000        NaN
75%       NaN  22.250000        NaN
max       NaN  23.000000        NaN

In [72]:
df.Name

0        Ankit
1    Aishwarya
2      Shaurya
3     Shivangi
Name: Name, dtype: object

In [6]:
D

{'Name': ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
 'Age': [23, 21, 22, 21],
 'University': ['BHU', 'JNU', 'DU', 'BHU']}

In [8]:
A = [1,2,3]
B = ["a", "b", "c"]

for x,y in zip(A,B):
    print(x,y)

1 a
2 b
3 c

In [13]:
# DataFrame from List
Name = ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi']
Age = [23, 21, 22, 21]
University = ['BHU', 'JNU', 'DU', 'BHU'] 
df = pd.DataFrame(zip(Name, Age, University), columns=['Nama', 'Umur', 'Universitas'])
df

        Nama  Umur Universitas
0      Ankit    23         BHU
1  Aishwarya    21         JNU
2    Shaurya    22          DU
3   Shivangi    21         BHU

In [14]:
list( range(5) )

[0, 1, 2, 3, 4]

In [12]:
# Index slicing operates similarly to Lists, but caution is required.
print(df.index)
df[1:3]

RangeIndex(start=0, stop=4, step=1)

        Nama  Umur Universitas
1  Aishwarya    21         JNU
2    Shaurya    22          DU

# <center><font color="blue"> OK, Let's Start!: Import-Loading Data</font></center>

<center><img alt="" src="images/meme-cartoon/Reading-and-Writing-Data-With-Pandas.jpg" style="height: 300px;" /></center>

# <center><font color="blue"> Case Study</font></center>

* Data Source: http://byebuyhome.com/
* Objective: To identify house prices that are below market value for investment purposes.
* Variables:
 - **Dist_Taxi** – distance to nearest taxi stand from the property
 - **Dist_Market** – distance to nearest grocery market from the property
 - **Dist_Hospital** – distance to nearest hospital from the property
 - **Carpet** – carpet area of the property in square feet
 - **Builtup** – built-up area of the property in square feet
 - **Parking** – type of car parking available with the property
 - **City_Category** – categorization of the city based on the size
 - **Rainfall** – annual rainfall in the area where property is located
 - **House_Price** – price at which the property was sold

<img alt="" src="images/property-investment-analysis.jpg" style="height: 250px;" />

# <center><font color="blue"> Import-Loading CSV / Excel Data via Pandas</font></center>

<img alt="" src="images/pandas load csv excel.png" style="height: 150px;" />

* Importing CSV file  https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
* Importing Excel file  https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
* Encodings https://docs.python.org/3/library/codecs.html#standard-encodings

In [15]:
file_ = 'data/price.csv'
try: # Running Locally, ensure "file_" is in the "data" folder
    price = pd.read_csv(file_)
except: # Running in Google Colab
    !mkdir data
    !wget -P data/ https://raw.githubusercontent.com/taudataanalytics/taudata-Academy/master/data/price.csv
    price = pd.read_csv(file_)
    
N, P = price.shape # Data Dimensions
print('rows = ', N, ', Columns (number of variables) = ', P)
print("Type of df Variable = ", type(price))
price

rows =  936 , Columns (number of variables) =  10
Type of df Variable =  <class 'pandas.core.frame.DataFrame'>

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price
0,1,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000
1,2,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000
2,3,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000
3,4,8301.0,11188.0,12289.0,1451.0,1748.0,Covered,CAT B,620,5373000
4,5,10510.0,12629.0,13921.0,1770.0,2111.0,Not Provided,CAT B,450,4662000
...,...,...,...,...,...,...,...,...,...,...
931,932,9297.0,12537.0,14418.0,1174.0,1429.0,Covered,CAT C,1110,5434000
932,933,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
933,934,9205.0,10418.0,14496.0,1118.0,1337.0,Open,CAT A,560,7227000
934,935,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
935,936,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000

# <center><font color="blue"> What about Excel Files?</font></center>
## <font color="green"> Due to deprecated support, the "openpyxl" module must be installed first</font>

* Importing Excel file  https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
* openpyxl https://openpyxl.readthedocs.io/en/stable/
<center><img alt="" src="images/meme-cartoon/openpyxl.jpg" style="height: 300px;" /></center>

In [18]:
!pip install openpyxl --q

In [16]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [24]:
file_ = 'data/price.xlsx'
try: # Running Locally 
    xl = pd.ExcelFile(file_)
except: # Running in Google Colab
    !mkdir data
    !wget -P data/ https://raw.githubusercontent.com/taudataanalytics/taudata-Academy/master/{file_}
    xl = pd.ExcelFile(file_, engine = 'openpyxl')

sheets_ = xl.sheet_names
print(sheets_)
price = xl.parse(sheets_[0], header=0) # It is good practice to avoid referencing sheet names directly

N, P = price.shape # Data Dimensions
print('rows = ', N, ', Columns (number of variables) = ', P)
print("Type of df Variable = ", type(price))
price

['price1', 'price2']
rows =  936 , Columns (number of variables) =  10
Type of df Variable =  <class 'pandas.core.frame.DataFrame'>

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price
0,1,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000
1,2,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000
2,3,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000
3,4,8301.0,11188.0,12289.0,1451.0,1748.0,Covered,CAT B,620,5373000
4,5,10510.0,12629.0,13921.0,1770.0,2111.0,Not Provided,CAT B,450,4662000
...,...,...,...,...,...,...,...,...,...,...
931,932,9297.0,12537.0,14418.0,1174.0,1429.0,Covered,CAT C,1110,5434000
932,933,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
933,934,9205.0,10418.0,14496.0,1118.0,1337.0,Open,CAT A,560,7227000
934,935,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
935,936,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000

# <center><font color="blue"> Prefer XLS or CSV in Data Science/Machine Learning/AI</font></center><br><font color="green">Why?</font>

<center><img alt="" src="images/excel_error.png" style="height: 300px;" /></center>

In [26]:
# "Peeking" at the first few rows of data
price.head(3)

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price
0,1,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000
1,2,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000
2,3,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000

In [27]:
# Tip: Use Transpose for High-Dimensional Data (data with numerous columns/variables)
price.head().transpose()

                     0             1             2        3             4
Observation          1             2             3        4             5
Dist_Taxi       9796.0        8294.0       11001.0   8301.0       10510.0
Dist_Market     5250.0        8186.0       14399.0  11188.0       12629.0
Dist_Hospital  10703.0       12694.0       16991.0  12289.0       13921.0
Carpet          1659.0        1461.0        1340.0   1451.0        1770.0
Builtup         1961.0        1752.0        1609.0   1748.0        2111.0
Parking           Open  Not Provided  Not Provided  Covered  Not Provided
City_Category    CAT B         CAT B         CAT A    CAT B         CAT B
Rainfall           530           210           720      620           450
House_Price    6649000       3982000       5401000  5373000       4662000

In [28]:
# "Peeking" at the last few rows of data
price.tail(7)

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price
929,930,7423.0,11708.0,13220.0,1200.0,1436.0,Open,CAT A,1060,7644000
930,931,15082.0,14700.0,19617.0,1299.0,1560.0,Open,CAT B,770,9661000
931,932,9297.0,12537.0,14418.0,1174.0,1429.0,Covered,CAT C,1110,5434000
932,933,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
933,934,9205.0,10418.0,14496.0,1118.0,1337.0,Open,CAT A,560,7227000
934,935,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
935,936,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000

In [29]:
# chosen at random
price.sample(10)

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price
532,533,5584.0,10514.0,11003.0,1244.0,1477.0,No Parking,CAT B,890,2784000
179,180,4692.0,5460.0,7531.0,1343.0,1599.0,Open,CAT B,870,4491000
90,91,7566.0,9599.0,16454.0,1287.0,1525.0,Not Provided,CAT A,1200,9018000
458,459,13925.0,14473.0,17746.0,1513.0,1820.0,Open,CAT B,520,6602000
441,442,7807.0,9674.0,12678.0,1161.0,1404.0,Covered,CAT C,430,5838000
734,735,8701.0,8969.0,12290.0,932.0,1120.0,Covered,CAT B,660,3559000
145,146,4945.0,10098.0,9241.0,1795.0,2187.0,Open,CAT A,300,7653000
455,456,4846.0,9003.0,10135.0,1373.0,1635.0,No Parking,CAT A,840,6104000
780,781,7684.0,7671.0,13192.0,1398.0,1683.0,Open,CAT B,490,4950000
679,680,9823.0,13861.0,14579.0,1334.0,1584.0,Not Provided,CAT B,840,5720000

# <center><font color="blue"> "loc" VS "iloc" in Pandas DataFrame</font></center>

<center><img alt="" src="images/dataframe loc iloc.png" style="height: 350px;" /></center>

In [30]:
price

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price
0,1,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000
1,2,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000
2,3,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000
3,4,8301.0,11188.0,12289.0,1451.0,1748.0,Covered,CAT B,620,5373000
4,5,10510.0,12629.0,13921.0,1770.0,2111.0,Not Provided,CAT B,450,4662000
...,...,...,...,...,...,...,...,...,...,...
931,932,9297.0,12537.0,14418.0,1174.0,1429.0,Covered,CAT C,1110,5434000
932,933,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
933,934,9205.0,10418.0,14496.0,1118.0,1337.0,Open,CAT A,560,7227000
934,935,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000
935,936,10915.0,17486.0,15964.0,1549.0,1851.0,Not Provided,CAT C,1220,7062000

In [33]:
# Replace "N" with the first index value in df_train
N = 999
try:
    print(price.loc[N]) 
except:
    print("Ensure the value N corresponds to the first index in df_train")

Ensure the value N corresponds to the first index in df_train

In [35]:
price.iloc[0]

Observation            1
Dist_Taxi         9796.0
Dist_Market       5250.0
Dist_Hospital    10703.0
Carpet            1659.0
Builtup           1961.0
Parking             Open
City_Category      CAT B
Rainfall             530
House_Price      6649000
Name: 0, dtype: object

# <center><font color="blue"> Iterating over a DataFrame (Very Important)</font></center>
### <font color="green"> Although frequently discouraged, many real-world scenarios necessitate this approach.</font>

<center><img alt="" src="images/pandas iteration.png" style="height: 350px;" /></center>
    
* https://www.dataindependent.com/pandas/pandas-iterate-over-rows/

In [38]:
# We can also iterate over a DataFrame (if necessary)
price['total_distance'] = None
for i, d in price.iterrows():
    price['total_distance'].loc[i] = d.Dist_Taxi + d.Dist_Market + d.Dist_Hospital

price.head()

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price,total_distance
0,1,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000,25749.0
1,2,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000,29174.0
2,3,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000,42391.0
3,4,8301.0,11188.0,12289.0,1451.0,1748.0,Covered,CAT B,620,5373000,31778.0
4,5,10510.0,12629.0,13921.0,1770.0,2111.0,Not Provided,CAT B,450,4662000,37060.0

In [40]:
# Apply utilizes "Cython" and is consequently faster
price['selling_price'] = price['House_Price'].apply(lambda x: x + 250000)
# a new column will be added to the "price" DataFrame
price.head(3)

,Observation,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price,total_distance,selling_price
0,1,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000,25749.0,6899000
1,2,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000,29174.0,4232000
2,3,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000,42391.0,5651000

# <center><font color="blue"> Removing variable(s) & Fixing Variable Type(s)</font></center>

<center><img alt="" src="images/pandas-dataframe-drop.png" style="height: 350px;" /></center>

In [41]:
# Note the command does not use "()" ==> Properties 
price.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Hospital', 'Carpet',
       'Builtup', 'Parking', 'City_Category', 'Rainfall', 'House_Price',
       'total_distance', 'selling_price'],
      dtype='object')

In [42]:
# Drop the first column as it is not useful (it is merely an "observation" index)
try: # It is good practice to always use Try-Except when performing a "drop" operation. Why?
    price.drop(["Observation"], axis=1, inplace=True) # The "inplace=True" parameter is important when working with large datasets.
    #price = price.drop(["Observation"], axis=1) # copy memory
except Exception as err_:
    print(err_)
    
print(price.columns)
price.head(3)

Index(['Dist_Taxi', 'Dist_Market', 'Dist_Hospital', 'Carpet', 'Builtup',
       'Parking', 'City_Category', 'Rainfall', 'House_Price', 'total_distance',
       'selling_price'],
      dtype='object')

,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price,total_distance,selling_price
0,9796.0,5250.0,10703.0,1659.0,1961.0,Open,CAT B,530,6649000,25749.0,6899000
1,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000,29174.0,4232000
2,11001.0,14399.0,16991.0,1340.0,1609.0,Not Provided,CAT A,720,5401000,42391.0,5651000

In [43]:
# Example: delete rows 1 and 3
price.drop(price.index[[0,2]], inplace=True) # Intentionally not using "inplace=True". Observe the result in the following cell

In [45]:
price.head()

,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Parking,City_Category,Rainfall,House_Price,total_distance,selling_price
1,8294.0,8186.0,12694.0,1461.0,1752.0,Not Provided,CAT B,210,3982000,29174.0,4232000
3,8301.0,11188.0,12289.0,1451.0,1748.0,Covered,CAT B,620,5373000,31778.0,5623000
4,10510.0,12629.0,13921.0,1770.0,2111.0,Not Provided,CAT B,450,4662000,37060.0,4912000
5,6665.0,5142.0,9972.0,1442.0,1733.0,Open,CAT B,760,4526000,21779.0,4776000
6,13153.0,11869.0,17811.0,1542.0,1858.0,No Parking,CAT A,1030,7224000,42833.0,7474000

In [48]:
price.iloc[4]

Dist_Taxi            13153.0
Dist_Market          11869.0
Dist_Hospital        17811.0
Carpet                1542.0
Builtup               1858.0
Parking           No Parking
City_Category          CAT A
Rainfall                1030
House_Price          7224000
total_distance       42833.0
selling_price        7474000
Name: 6, dtype: object

In [ ]:
price.head(4) # What happened?

In [ ]:
# In machine learning/AI/Data Science, understanding Data Structures is essential for comprehension
print( "type = ", type(price.index[[0,2]]),  "\nvalue = ",price.index[[0,2]]) 
# drop by integer "index" for rows & column name + axis=1 to drop columns

In [ ]:
# Delete rows based on a condition
price.drop(price[(price.House_Price > 6500000) & (price.House_Price < 9000000)].index, inplace=True)
# To remember, imagine the "parameter" for drop is an integer index, as explained in the previous cell
print(price.shape)
price.head(7)

# <center><font color="blue"> Correcting Variable Types: "dtype" & "info"</font></center>

### <font color="green"> A crucial aspect of understanding ML/AI/Data Science, in both theory and application, is "Data Structure"</font>
    
<center><img alt="" src="images/pandas_dtypes.png" style="height: 350px;" /></center>

In [49]:
# data type of each column
# It is mandatory to check if the data types are correct.
# Note that a DataFrame, like all variables in Python, is treated as an object
price.info()

<class 'pandas.core.frame.DataFrame'>
Index: 934 entries, 1 to 935
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dist_Taxi       921 non-null    float64
 1   Dist_Market     921 non-null    float64
 2   Dist_Hospital   933 non-null    float64
 3   Carpet          926 non-null    float64
 4   Builtup         919 non-null    float64
 5   Parking         934 non-null    object
 6   City_Category   934 non-null    object
 7   Rainfall        934 non-null    int64
 8   House_Price     934 non-null    int64
 9   total_distance  921 non-null    object
 10  selling_price   934 non-null    int64
dtypes: float64(5), int64(3), object(3)
memory usage: 119.9+ KB

In [50]:
price.dtypes # Provides less information, but note the data structure (which is more useful).

Dist_Taxi         float64
Dist_Market       float64
Dist_Hospital     float64
Carpet            float64
Builtup           float64
Parking            object
City_Category      object
Rainfall            int64
House_Price         int64
total_distance     object
selling_price       int64
dtype: object

In [57]:
# dataframe types: https://pbpython.com/pandas_dtypes.html
price['Parking'] = price['Parking'].astype('category')
price['City_Category'] = price['City_Category'].astype('category')
price['total_distance'] = price['total_distance'].astype('float64')

price.info()

<class 'pandas.core.frame.DataFrame'>
Index: 934 entries, 1 to 935
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dist_Taxi       921 non-null    float64
 1   Dist_Market     921 non-null    float64
 2   Dist_Hospital   933 non-null    float64
 3   Carpet          926 non-null    float64
 4   Builtup         919 non-null    float64
 5   Parking         934 non-null    category
 6   City_Category   934 non-null    category
 7   Rainfall        934 non-null    int64
 8   House_Price     934 non-null    int64
 9   total_distance  921 non-null    float64
 10  selling_price   934 non-null    int64
dtypes: category(2), float64(6), int64(3)
memory usage: 107.4 KB

# <center><font color="blue"> Variable Type Selection</font></center>
### <font color="green"> Slicing data based on Type is critical, as certain visualizations or algorithms are designed for specific data types.</font>
    
<center><img alt="" src="images/pandas subsetting.png" style="height: 250px;" /></center>

In [53]:
# If only the column names are required, this can be done to conserve memory
numVar = price.select_dtypes(include = ['float64', 'int64']).columns
numVar.to_list()

['Dist_Taxi',
 'Dist_Market',
 'Dist_Hospital',
 'Carpet',
 'Builtup',
 'Rainfall',
 'House_Price',
 'selling_price']

In [54]:
# Select only variables of a specific type
numVar = price.select_dtypes(include = ['float64', 'int64'])
numVar.head() # Note that numVar is a new DataFrame variable! (Exercise caution with large datasets)

,Dist_Taxi,Dist_Market,Dist_Hospital,Carpet,Builtup,Rainfall,House_Price,selling_price
1,8294.0,8186.0,12694.0,1461.0,1752.0,210,3982000,4232000
3,8301.0,11188.0,12289.0,1451.0,1748.0,620,5373000,5623000
4,10510.0,12629.0,13921.0,1770.0,2111.0,450,4662000,4912000
5,6665.0,5142.0,9972.0,1442.0,1733.0,760,4526000,4776000
6,13153.0,11869.0,17811.0,1542.0,1858.0,1030,7224000,7474000

In [58]:
# Select only variables of a specific type
catVar = price.select_dtypes(include = ['object', 'category'])
catVar.head(3)

        Parking City_Category
1  Not Provided         CAT B
3       Covered         CAT B
4  Not Provided         CAT B

In [60]:
# get all unique values of a variable/column
for col in catVar.columns:
    print(col,': ', set(price[col].unique()))

Parking :  {'Open', 'Covered', 'No Parking', 'Not Provided'}
City_Category :  {'CAT C', 'CAT A', 'CAT B'}

# <center><font color="blue"> Selecting data variables manually</font></center>

In [66]:
# Choosing some columns manually
X = price[['House_Price','Dist_Market']] # Note the double square brackets "[[]]"
X.head(3)

   House_Price  Dist_Market
1      3982000       8186.0
3      5373000      11188.0
4      4662000      12629.0

In [ ]:
# Slicing DataFrame - Just like query in SQL
price[price["City_Category"] == "CAT B"].drop("City_Category", axis=1).head()

In [ ]:
# Slicing DataFrame - Just like query in SQL
X = price[price["Parking"].isin(["Open","Covered"])]
X = X[X["City_Category"] == "CAT B"].drop("City_Category", axis=1)
X.head()

<center><h1><strong><font color="blue"> Data Wrangling</font></strong></h1></center>

* Data wrangling is the process of transforming raw data into a usable format. This is also referred to as data munging.

* Data wrangling encompasses a series of processes designed to explore, transform, and validate raw datasets, converting them from a complex, 'dirty' state into high-quality data. We can use this wrangled data to generate valuable insights and inform business decisions.

* Data Wrangling is an iterative process.

<img alt="" src="images/data-wrangling.jpg"/>

<center><h1><strong><font color="blue"> Core data wrangling types </font></strong></h1></center>

<img alt="" src="images/Data-Wrangling-Types.png"/>

<center><h1><strong><font color="blue"> Hierarchical Indexing </font></strong></h1></center>

* Hierarchical indexing is an important feature of pandas that enables you to have multiple (two or more) index levels on an axis
* Source: [2]

<img alt="" src="images/Hierarchical-index-in-Pandas-dataframe.png"/>

In [73]:
data = pd.DataFrame(data=np.random.randn(9), 
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

            0
a 1 -2.337087
  2 -1.351232
  3 -0.950834
b 1  0.548364
  3  0.603041
c 1 -0.169718
  2 -0.847060
d 2 -1.446852
  3 -0.045213

In [74]:
data.loc['a'].loc[1]

0   -2.337087
Name: 1, dtype: float64

In [75]:
data.iloc[0]

0   -2.337087
Name: (a, 1), dtype: float64

In [76]:
data.loc[['b', 'd', 'a']] # Note the number of square brackets!....

            0
b 1  0.548364
  3  0.603041
d 2 -1.446852
  3 -0.045213
a 1 -2.337087
  2 -1.351232
  3 -0.950834

In [77]:
data.loc['b' : 'd'] # Note the number of square brackets!.... It is different when slicing!.

            0
b 1  0.548364
  3  0.603041
c 1 -0.169718
  2 -0.847060
d 2 -1.446852
  3 -0.045213

# Caution: Indexing is handled slightly differently in a "Series"

In [ ]:
data2 = pd.Series(np.random.randn(9), 
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data2['b']

In [ ]:
data2.loc[:, 2] # Caution: This will raise an error if "data2" is a DataFrame!...

<center><h1><strong><font color="blue"> What is Hierarchical Indexing Used For?</font></strong></h1></center>

Hierarchical indexing plays an important role in reshaping data and group-based
operations like forming a pivot table. For example, you could rearrange the data into
a DataFrame using its unstack method

<img alt="" src="images/stack-unstack-in-Pandas-dataframe.png"/>

In [78]:
data

            0
a 1 -2.337087
  2 -1.351232
  3 -0.950834
b 1  0.548364
  3  0.603041
c 1 -0.169718
  2 -0.847060
d 2 -1.446852
  3 -0.045213

In [79]:
data.unstack()

          0
          1         2         3
a -2.337087 -1.351232 -0.950834
b  0.548364       NaN  0.603041
c -0.169718 -0.847060       NaN
d       NaN -1.446852 -0.045213

In [80]:
data.unstack().stack() # Observe the data structure

            0
a 1 -2.337087
  2 -1.351232
  3 -0.950834
b 1  0.548364
  3  0.603041
c 1 -0.169718
  2 -0.847060
d 2 -1.446852
  3 -0.045213

# Rename Index (for clarity)

In [81]:
data = np.arange(12).reshape((4, 3))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [82]:
frame = pd.DataFrame(data,
    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
    columns=[['Ohio', 'Ohio', 'Colorado'],
    ['Green', 'Red', 'Green']])

frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [83]:
# Understand these two commands as modifications to the properties of the "frame" Object! ... 
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [85]:
# Selecting Groups of Columns
# This greatly facilitates subsequent EDA ==> No longer a novice Data Analyst.
frame['Ohio'].describe()

color     Green        Red
count  4.000000   4.000000
mean   4.500000   5.500000
std    3.872983   3.872983
min    0.000000   1.000000
25%    2.250000   3.250000
50%    4.500000   5.500000
75%    6.750000   7.750000
max    9.000000  10.000000

<center><h1><strong><font color="blue"> Reordering and Sorting Levels </font></strong></h1></center>

In [ ]:
frame.swaplevel('key1', 'key2')

In [ ]:
# Can also be sorted
frame.sort_index(level=1) # Change "1" to "0" to understand this operation.

<center><h1><strong><font color="blue"> Indexing with a DataFrame’s columns </font></strong></h1></center>

## This is frequently required when working with real-world data

In [90]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
     'c': ['one', 'one', 'one', 'two', 'two',
     'two', 'two'],
     'd': [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [91]:
frame2 = frame.set_index(['c', 'd']) # ==> Creates an index based on the values from columns "c" and "d"
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [92]:
frame2.loc['one'].loc[1:2].describe()

              a         b
count  2.000000  2.000000
mean   1.500000  5.500000
std    0.707107  0.707107
min    1.000000  5.000000
25%    1.250000  5.250000
50%    1.500000  5.500000
75%    1.750000  5.750000
max    2.000000  6.000000

In [93]:
frame.set_index(['c', 'd'], drop=False) # If we want to retain c and d as columns (though the use case is unclear)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [94]:
# Resetting the index is typically necessary after making numerous modifications to the DataFrame
# Or upon completing Data Preprocessing/EDA
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

<center><h1><strong><font color="blue"> Combining and Merging Datasets </font></strong></h1></center>

<img alt="" src="images/join-in-Pandas-dataframe.png"/>

There are 3 types:
* pandas.merge connects rows in DataFrames based on one or more keys. This will be familiar to users of SQL or other relational databases, as it implements database join operations.
* pandas.concat concatenates or “stacks” together objects along an axis.
* The combine_first instance method enables splicing together overlapping data to fill in missing values in one object with values from another.

<center><h1><strong><font color="blue"> Database-Style DataFrame Joins (Merge/Join) </font></strong></h1></center>

In [95]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
     'data1': range(7)})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [96]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
    'data2': range(3)})
df2

  key  data2
0   a      0
1   b      1
2   d      2

# many-to-one join

the data in df1 has multiple rows labeled a
and b, whereas df2 has only one row for each value in the key column. Calling merge
with these objects we obtain:

## Which Data is Missing? And Why?

In [97]:
pd.merge(df1, df2, on='key')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

# What if the column names are different?

In [98]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
    'data1': range(7)})
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [99]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
    'data2': range(3)})

df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [101]:
pd.merge(df3, df4, right_on='rkey', left_on='lkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [102]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')[['lkey', 'data1', 'data2']]

  lkey  data1  data2
0    b      0      1
1    b      1      1
2    a      2      0
3    a      4      0
4    a      5      0
5    b      6      1

# Inner join

You may notice that the 'c' and 'd' values and associated data are missing from the
result. By default merge does an 'inner' join; the keys in the result are the intersec‐
tion, or the common set found in both tables.

<img alt="" src="images/join-in-Pandas-dataframe.png"/>

# Outer Join

Other possible options are 'left', 'right', and 'outer'. The outer join takes the union of the keys, combining the
effect of applying both left and right joins:

In [106]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [108]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [105]:
pd.merge(df1, df2, how='outer') # Observe the output.

  key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

# Many-to-many merges 

* well-defined, though not necessarily intuitive, behavior
* Many-to-many joins form the Cartesian product of the rows.

In [109]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
     'data1': range(6)})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [110]:
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
    'data2': range(5)})

df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [111]:
pd.merge(df1, df2, on='key', how='left')

   key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

Since there were three
'b' rows in the left DataFrame and two in the right one, there are six 'b' rows in the
result. The join method only affects the distinct key values appearing in the result:

In [112]:
pd.merge(df1, df2, how='inner')

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

<center><h1><strong><font color="blue"> merge with multiple keys </font></strong></h1></center>

* When joining columns-on-columns, the indexes on the passed DataFrame objects are discarded.

In [113]:
df1 = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
    'key2': ['one', 'two', 'one'],
    'lval': [1, 2, 3]})
df1

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [114]:
df2 = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
     'key2': ['one', 'one', 'one', 'two'],
     'rval': [4, 5, 6, 7]})
df2

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [115]:
pd.merge(df1, df2, on=['key1', 'key2'], how='outer')

  key1 key2  lval  rval
0  bar  one   3.0   6.0
1  bar  two   NaN   7.0
2  foo  one   1.0   4.0
3  foo  one   1.0   5.0
4  foo  two   2.0   NaN

# overlapping column names

* While you can address the overlap manually (e.g., rename columns), merge has a suffixes option for specifying strings to append to overlapping names in the left and right DataFrame objects

In [120]:
df1

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [119]:
df2

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [118]:
pd.merge(df1, df2, on='key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [121]:
pd.merge(df1, df2, on='key1', suffixes=('_one', '_two'))

  key1 key2_one  lval key2_two  rval
0  foo      one     1      one     4
1  foo      one     1      one     5
2  foo      two     2      one     4
3  foo      two     2      one     5
4  bar      one     3      one     6
5  bar      one     3      two     7

<center><h1><strong><font color="blue"> Merging on Index </font></strong></h1></center>

In [122]:
df1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
    'value': range(6)})
df1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [123]:
df2 = pd.DataFrame({'group_val': [35, 7]}, index=['a', 'b'])
df2

   group_val
a         35
b          7

In [124]:
pd.merge(df1, df2, left_on='key', right_index=True)

  key  value  group_val
0   a      0         35
1   b      1          7
2   a      2         35
3   a      3         35
4   b      4          7

# Concatenating Along an Axis

In [125]:
# Concat in DataFrame

df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
    columns=['one', 'two'])
df1

   one  two
a    0    1
b    2    3
c    4    5

In [126]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
    columns=['three', 'four'])
df2

   three  four
a      5     6
c      7     8

In [127]:
pd.concat([df1, df2], axis=1) # , keys=['level1', 'level2']
#Observe the index

   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

<center><h1><strong><font color="blue"> Data Aggregation and Group Operations </font></strong></h1></center>

<img alt="" src="images/Aggregrate-Groups-Pandas-dataframe.png"/>

* pandas provides a flexible groupby interface, enabling you to slice, dice, and summarize datasets in a natural way.
* Aggregation of time series data, a special use case of groupby, is referred to as resampling.

<center><h1><strong><font color="blue"> 1. GroupBy Mechanics </font></strong></h1></center>

<img alt="" src="images/Split-Apply-Combine-Pandas-dataframe.png"/>

* Hadley Wickham, an author of many popular packages for the R programming lan‐
guage, coined the term split-apply-combine for describing group operations.

In [128]:
import pandas as pd , numpy as np

df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
    'key2' : ['one', 'two', 'one', 'two', 'one'],
    'data1' : [1,2,3,4,5],
    'data2' : [6,7,8,9,10]})
df

  key1 key2  data1  data2
0    a  one      1      6
1    a  two      2      7
2    b  one      3      8
3    b  two      4      9
4    a  one      5     10

In [129]:
grouped = df.groupby(df['key1']).sum()
grouped

           key2  data1  data2
key1
a     onetwoone      8     23
b        onetwo      7     17

In [ ]:
grouped = df['data1 data2'.split()].groupby(df['key1']).mean()
grouped

In [ ]:
grouped[['data1', 'data2']].mean()

In [ ]:
means = df.groupby([df['key1'], df['key2']]).mean()
means

In [ ]:
means.loc['a'].loc['one'].describe()

In [ ]:
df[['key1', 'data1', 'data2']].groupby('key1').mean()

# You may have noticed in the first case df.groupby('key1').mean() that there is no key2 column in the result. 
# Because df['key2'] is not numeric data, it is said to be a nuisance column, which is therefore excluded from the result.

In [ ]:
# Even with numerical data, we sometimes want to know the number of occurrences (frequency)
df.groupby(['key1', 'key2']).size()

# GroupBy can be flexible by choosing which columns to group by

* While also renaming the groupBy result

In [ ]:
people = pd.DataFrame(np.random.randn(5, 5),
    columns=['a', 'b', 'c', 'd', 'e'],
    index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])
people

In [ ]:
d = {'a': 'takeHomePay', 'b': 'takeHomePay', 'c': 'blue', 'd': 'blue', 'e': 'takeHomePay', 'f' : 'orange'}
d

In [ ]:
people.groupby(d, axis=1).sum()

<center><h1><strong><font color="blue"> Data Aggregation </font></strong></h1></center>

<img alt="" src="images/GroupBy-Pandas-dataframe.png"/>

* Aggregations refer to any data transformation that produces scalar values from
arrays. 
* This is not limited to the functions in the table above

In [130]:
df

  key1 key2  data1  data2
0    a  one      1      6
1    a  two      2      7
2    b  one      3      8
3    b  two      4      9
4    a  one      5     10

In [131]:
df[['key1','data1','data2']].groupby('key1').mean()

         data1     data2
key1
a     2.666667  7.666667
b     3.500000  8.500000

# Custom Aggregate Function 

### Note: This is very important to understand

In [132]:
def RangeData(arr):
    return arr.max() - arr.min()

In [133]:
df[['key1','data1','data2']].groupby('key1').agg(RangeData)

      data1  data2
key1
a         4      4
b         1      1

# Apply on DataFrame

* Also very important for code efficiency

In [ ]:
def sum_square(x):
    return x.sum()**2+1

data = {
  "x": [5, 4, 3],
  "y": [2, 1, 7]
}
df = pd.DataFrame(data)
df

In [ ]:
df.apply(sum_square)

<center><h1><strong><font color="blue"> Pivot Tables and Cross-Tabulation </font></strong></h1></center>

A pivot table is a data summarization tool frequently found in spreadsheet programs
and other data analysis software. It aggregates a table of data by one or more keys,
arranging the data in a rectangle with some of the group keys along the rows and
some along the columns. Pivot tables in Python with pandas are made possible
through the groupby

In [3]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
tips[['day', 'smoker','tip','total_bill']].pivot_table(index=['day', 'smoker'])

                  tip  total_bill
day  smoker
Thur Yes     3.030000   19.190588
     No      2.673778   17.113111
Fri  Yes     2.714000   16.813333
     No      2.812500   18.420000
Sat  Yes     2.875476   21.276667
     No      3.102889   19.661778
Sun  Yes     3.516842   24.120000
     No      3.167895   20.506667

# CrossTab

* A cross-tabulation (or crosstab for short) is a special case of a pivot table that computes group frequencies.

In [5]:
pd.crosstab(tips.day, tips.smoker)

smoker  Yes  No
day
Thur     17  45
Fri      15   4
Sat      42  45
Sun      19  57

# Basic Visualization in Python

<img alt="" src="images/eda/Python_Vis_Map.png" />

<img alt="" src="images/eda/All-Visualizations.png" style="height: 700px;" />

In [ ]:
# From the previous Module - PreProcessed Data can also be loaded
price = pd.read_csv('data/price.csv')
price.drop("Observation", axis=1, inplace=True)
price.drop_duplicates(inplace=True)
price['Parking'] = price['Parking'].astype('category')
price['City_Category'] = price['City_Category'].astype('category')
price2 = price[np.abs(price.House_Price - price.House_Price.mean())<=(2*price.House_Price.std())]
price2.info()

In [ ]:
p= sns.catplot(x="Parking", y="House_Price", data=price2, hue='Parking')
# What can be observed from this result?

In [ ]:
# It is also possible to plot using information from 3 variables simultaneously
# (to observe potential interaction factors)
p= sns.catplot(x="Parking", y="House_Price", hue="City_Category", kind="swarm", data=price2)

# <center><font color="blue">1D Visualization: Bar Chart / Count Plot</font></center>
<center><img alt="" src="images/barchart.png" style="height: 300px;" /></center>

Image Source: https://datavizcatalogue.com/methods/bar_chart.html

# <center><font color="blue">Caution: Bar Chart vs. Histogram </font></center>
<center><img alt="" src="images/barchart_vs_histogram.png" style="height: 300px;" /></center>

image Source: https://www.mathsisfun.com/data/bar-graphs.html

In [ ]:
ax = sns.countplot(y = 'Parking', hue = 'City_Category', palette = 'muted', data=price2)

In [ ]:
# "SubPlot" demonstration, but using a different dataset as the 'price' data only has 2 categorical variables.

tips=sns.load_dataset('tips') # Built-in data from the Seaborn Module ... will be explained further below.
categorical = tips.select_dtypes(include = ['category']).columns

fig, ax = plt.subplots(2, 2, figsize=(12, 6))
for variable, subplot in zip(categorical, ax.flatten()):
    sns.countplot(x=tips[variable], ax=subplot)

# 1D Visualization: Pie Chart

<img alt="" src="images/piechart.png" />

## Image Source: https://datavizcatalogue.com/methods/pie_chart.html

In [ ]:
plot = price2.City_Category.value_counts().plot(kind='pie')

# <center><font color="blue">Box Plot</font></center>

<center><img alt="" src="images/boxplot.png" style="height: 600px;" /></center>

* Lower Extreme: $Q_1 - 1.5(Q_3-Q_1)$  Upper Extreme $Q_3 + 1.5(Q_3-Q_1)$
* Source: https://datavizcatalogue.com/methods/box_plot.html & https://lsc.deployopex.com/box-plot-with-jmp/

In [ ]:
p = sns.catplot(x="Parking", y="House_Price", hue="City_Category", kind="box", data=price2)

# <center><font color="blue">Histogram</font></center>

<center><img alt="" src="images/histogram.png" style="height: 300px;" /></center>

image source: https://datavizcatalogue.com/methods/histogram.html

In [ ]:
numerical = price2.select_dtypes(include = ['int64','float64']).columns

price2[numerical].hist(figsize=(15, 6), layout=(2, 4));

# <center><font color="blue">Scatter Plot</font></center>

<center><img alt="" src="images/scatter_plot.png" style="height: 600px;" /></center>

image source: https://datavizcatalogue.com/methods/scatterplot.html

In [ ]:
# Let's observe a subset and try grouping by "City_Category"
p = sns.pairplot(price2[['House_Price','Builtup','Dist_Hospital','City_Category']], hue="City_Category")
# Are there any interesting patterns?

# Checking Correlations

In [ ]:
price2_corr = price2['Dist_Taxi Dist_Market Dist_Hospital House_Price Rainfall'.split()].corr()
corr2 = price2_corr.corr() # We already examined SalePrice correlations
plt.figure(figsize=(12, 10))
sns.heatmap(corr2[(corr2 >= 0.7) | (corr2 <= -0.7)], 
            cmap='viridis', vmax=1.0, vmin=-1.0, linewidths=0.1,
            annot=True, annot_kws={"size": 14}, square=True);

<center><h2><strong><font color="blue">End of Module</font></strong></h2></center>
<hr>
<center><img alt="" src="images/meme-cartoon/pandas-meme.jpg"/></center>
<center><img alt="" src="images/meme-cartoon/data-wrangling-meme.jpg"/></center>

# References:

1. Rattenbury, Tye, et al. Principles of data wrangling: Practical techniques for data preparation. " O'Reilly Media, Inc.", 2017.

2. McKinney, Wes. Python for data analysis: Data wrangling with Pandas, NumPy, and IPython. " O'Reilly Media, Inc.", 2012.